baseURL = "http://missamanda.blog/"
languageCode = "en-us"
title = "Miss Amanda"
theme = "personal-web"
publishDir = "docs"

[params.sidebar]
  logo = "mandy.jpg"
  backgroundImage = "toddler.jpg"

[params.intro]
  main = "Hi, I'm Miss Amanda :wave:"
  sub = "I'm a Montessori teacher"

[params.assets]
  customCSS = "/style.css"

[taxonomies]
  age = "ages"
  skill = "skills"
  curriculum = "curriculum"

[menu]

[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About"
  url = "/about/"
  weight = -120

[[menu.main]]
  identifier = "lesson-plans"
  name = "Lesson Plans"
  title = "Lesson Plans"
  url = "/lesson-plan/"
  weight = -110

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  title = "Blog"
  url = "/post/"
  weight = -100

[markup.goldmark.renderer]
  unsafe = true
